baseURL: "https://anthonyofseattle.github.io"
languageCode: "en-us"
title: "AnthonyOfSeattle"
theme: "./.."
relativeURLs: true

googleanalytics: G-3X8Q5FWDPQ
disqusShortname:
Paginate: 3
markup:
  goldmark:
    renderer:
      unsafe: true

taxonomies:
  tag: "tags"
  category: "categories"

enableEmoji: true
params:
  version: 3
  customCSS: false

  favicon: "/images/fav.png"
  description: "A high performance hugo theme for personal portfolio and blog."

  # Navbar Menus
  # customMenus:
  #   - name: "Blog"
  #     Url: "/blog"

  # home
  disable_home: false
  profile_image: "/images/profile.png"
  name: "Anthony Barente"
  namecolor: ffc107
  profession: "Proteomics PhD Candidate at UW Genome Sciences"
  github: "https://github.com/AnthonyOfSeattle"
  linkedin: "https://www.linkedin.com/in/anthonyofseattle"
  twitter: "https://twitter.com/anthonybarente"

  # About
  disable_about: false
  descripe_l1_person: "Proteins are the fundamental unit of cellular function and understanding how cells regulate the production and dynamics of these molecules promises to transform our understanding of biology. As datasets and public repositories grow, it is more important than ever to make the information available to researchers. As a data scientist and mass spectrometrist, I work to bridge the gap between raw data and biological insight through fast extensible code and automated analyses."
  descripe_l2_person: "Currently, I am a PhD candidate in the Villén lab at UW Genome Sciences. Here I build tools and repositories to improve the study of protein post translational modifications. Sometimes, I put together smaller analyses of individual datasets, and I am always looking for new interesting questions. Have a look at my projects posted below, and feel free to get in contact if you would like to work together."

  # Experience
  disable_experience: true
  experience:
    - company: "University Of Washington"
      role: "Graduate Research Assistant"
      startdate: Sept 2016
      enddate: present
      featuredpoints:
        - point: Lead backend developer for a product.
        - point: Created a frontend design for a product.
    - company: "Pacific Northwest National Laboratories"
      role: "PhD Intern"
      startdate: June 2020
      enddate: Sept 2020
      featuredpoints:
        - point: Lead backend developer for a product.
        - point: Created a frontend design for a product.

  # Education
  disable_education: true
  education:
    - degree: "PhD"
      branch: "Genome Sciences"
      university: "University Of Washington"
      startedyear: "Sept 2016"
      graduation: "March 2019"
    - degree: "BS"
      branch: "Molecular & Cellular Biology"
      university: "Western Washington University"
      startedyear: "Sept 2011"
      graduation: "Dec 2015"

  # Projects
  disable_projects: false
  projects:
    - name: "Phosphopedia"
      img: /images/project.jpg
      githublink: "https://github.com/AnthonyOfSeattle/Phosphopedia"
      featuredlink: "https://phosphopedia.gs.washington.edu/PhosphoproteomicsAssay/"
      description: "Centralized repository for building targeted Phosphoproteomics assays."
    - name: "pyAscore"
      img: /images/project.jpg
      githublink: "https://github.com/AnthonyOfSeattle/pyAscore"
      featuredlink: "/"
      description: "A python module for fast post translational modification localization, powered by Cython."

  # Achievements
  disable_achievements: true
  achievements:
    - title: Competition winner
      description: We are developed a product which can help others.
      img: /images/achiv.jpg
      url: https://example.com
    - title: Competition winner
      description: We are developed a product which can help others.
      img: /images/achiv.jpg
      # url: https://example.com
    - title: Competition winner
      description: We are developed a product which can help others.
      img: /images/achiv.jpg
    - title: Competition winner
      description: We are developed a product which can help others.
      img: /images/achiv.jpg

  # Contact
  disable_contact: false
  contact_content: My inbox is always open. Whether you have a question or just want to say hi, I'll try my best to get back to you!
  email: "valenta4@uw.edu"

  # Footer
  socialiconfooter: true
  recentposts: false

  # Blog
  showdescription: false
  tweet: true
